### ISSUE TITLE
Trend of 2D Side Scrollers and Popularity

### ISSUE THREAD

**Issue by aire39** [AhmadAlkadi/RollingKnight#10]
How popular are these games
* How many people seem to play these games
* How well do these seem to sell
* The median price
* Sells

Would this game be worth making fully. We should look into Steam to find these statistics.

**Comment by AhmadAlkadi** [comment]
Most of my information here has been provided by gamedev.net, SteamDB, and VG Insights. One of the most played games that is very similar to the project we are going for is BattleBlock Theater which peaked at 14,781 players according to steamDB and another example that also came out recently which gained a lot of popularity was Pizza Tower which peaked at 9,074 players. Unfortunately they will not be able to hold records of above 500,000 players it is still impressive to be above the 5,000 threshold which a lot of games struggle to reach. Lets use the most recent example which is pizza tower to show all the stats of the revenue and unit sold. Pizza Tower was able to sell 1.2m units and it also has a $17.6m gross revenue. lets also look at BattleBlock Theater which sold around 5.1 units and has a $43.7m gross revenue. From the games that were mentioned and from other games the median price of the selling point for these game is around $19.99 to $24.99 and when the go on seal they go to around $4.99 to $14.99. According to my research Indie games developers do not like to talk about how much it coasts to make their games or some times even the time it took to make their game. In my theory from what I have been finding is that it will coast around $100,000 to $500,000 but this also depends on the amount of people that are working and a lot of 2D platformer games seem to be a either a solo project where the person just wanted to show his idea to the world or a group of friends that decided to make a game, but for our case of having a full development team because it is an indie development team most of the time the split will be even between the stuff, and they can not hire too many members because of the limited budget.
